### ISSUE TITLE
ModMenu icon overlap

### ISSUE THREAD

**Issue by Felix14-v2** [TerminalMC/Flashside#1]
### Mod Version

0.1.2

### Mod Loader

Fabric

### Minecraft Version

1.21.3

### Bug Description

![image](https://github.com/user-attachments/assets/c76891f7-15d8-4179-bd6b-95ea0e838220)

### Expected Behavior

Maybe shift the button to the right if the ModMenu icon is present? No idea, honestly

### Reproduction Steps

1. Install both Flashside and ModMenu
2. Launch Minecraft
3. Enable icon
4. Enter a world
5. Open pause menu
6. See the 

### Log File

[latest.log](https://github.com/user-attachments/files/18087019/latest.log)

**Comment by NotRyken** [comment]
Thanks for reporting. I've redesigned Flashside to allow it to shift the ModMenu button down when the Flashback buttons are active. If you want the ModMenu button to be in a fixed location, you can set it to always stay on top in config.
