### ISSUE TITLE
Toggle flashback buttons placement

### ISSUE THREAD

**Issue by leeineian** [TerminalMC/Flashside#2]
### Before you open a new issue;

- [x] **Are you requesting either a new feature or an improvement of existing  functionality?** If you want to request an update or backport, please use Discord.
- [X] **Have you checked whether a similar request already exists (either open or closed)?**  If your idea has been requested previously, please comment there instead.
- [X] **Have you checked whether the feature already exists on the latest version?** If you want to request that an existing feature be backported, please use Discord.

### Request Description

Adds a toggle to override flashback recording buttons, shifting its placement on either side (left or right) of the game menu and title screen

**Comment by NotRyken** [comment]
Added in `v0.3.0`, but do note that as doing this sort of thing is inherently very brittle, the feature may be removed if it becomes a problem.

**Comment by leeineian** [comment]
Okay thank you very much dev!! 🙇

**Comment by leeineian** [comment]
Oh the flashside button in the title screen refuses to align downwards, despite changing the settings to different values - could the "start row" option have individual values for the title and and game menu?

![image](https://github.com/user-attachments/assets/ed00ac3e-0ce0-44dc-b27b-80b29c4cbeb1)

**Comment by NotRyken** [comment]
Hmm. In theory yes, but I'll gave to look into it more to figure out if that's safe to do.

**Comment by NotRyken** [comment]
Okay so this is sort of done in `v0.4.0` when using the ModMenu icon button, but I'm entirely confident that it wasn't worth the amount of time it took so if this breaks at some point you should expect it to be removed. Flashside is supposed to be a simple edit to the pause screen, at the end of the day.

**Comment by leeineian** [comment]
No worries thank you again for looking into it 🙇
